logging:
  level:
    com.vcs.observer: debug

client:
  vcs:
    github:
      url: https://api.github.com
      acceptVersion: application/vnd.github.v3+json
      connect-timeout: 10 # seconds
      read-timeout: 30 # seconds
      follow-redirects: true

github:
  batch-size: 100